services:
  - type: web
    name: sigo-com-fe-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: https://sigocomfe.vercel.app
      - key: NODE_ENV
        value: production
